# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Movie Explorer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Movie Explorer

  pod 'Alamofire', '~> 5.6'
  pod 'Moya', '~> 15.0'
  pod 'SDWebImage', '~> 5.15'
  pod 'Toast-Swift', '~> 5.0'

end
